### ISSUE TITLE
[Inspeção] Filtro De Faturas

### ISSUE THREAD

**Issue by Thulio-Carvalho** [Thulio-Carvalho/vev-assignment-2#16]
No caso de teste da linha 87 na classe `ClienteTeste` (`testFiltraFaturasMaioresQue4000ClienteSul`) identifiquei um problema:

São adicionadas duas faturas a um cliente do sul (de **4000** e **4200**, respectivamente), e **o teste retorna OK caso, após a filtragem de faturas, não houverem faturas para o cliente.** 

Entretanto, a especificação define que uma fatura deve ser removida se:

> Se o valor da fatura for maior que 4000 e pertencer a algum estado da região Sul do Brasil.

Portanto, **deveria haver uma fatura após a filtragem**, dado que a fatura de 4000 não se encaixa no critério.

**Comment by augustogs** [comment]
Corrigido.
